export interface DeityRelations {
  father?: string;      // 父神ID
  mother?: string;      // 母神ID
  spouse?: string[];    // 配偶者ID（複数可）
  children?: string[];  // 子神ID
  siblings?: string[];  // 兄弟姉妹ID
}

export interface Shrine {
  id: string;
  deity: string;
  deityReading: string;
  name: string;
  location: string;
  lat: number;
  lng: number;
  description: string;
  mythology: string;
  blessing: string;
  category: string;
  relations?: DeityRelations;
}

export const shrines: Shrine[] = [
  // === 造化三神 ===
  {
    id: "amenominakanushi",
    deity: "天之御中主神",
    deityReading: "アメノミナカヌシノカミ",
    name: "東京大神宮",
    location: "東京都千代田区",
    lat: 35.6997,
    lng: 139.7494,
    description: "宇宙の根源神。天地開闢の際、最初に現れた神。",
    mythology: "古事記の冒頭、高天原に最初に成った神。独神として現れ、すぐに身を隠した。",
    blessing: "開運招福、事始め",
    category: "造化三神",
  },
  {
    id: "takamimusubi",
    deity: "高御産巣日神",
    deityReading: "タカミムスビノカミ",
    name: "高天彦神社",
    location: "奈良県御所市",
    lat: 34.4089,
    lng: 135.7347,
    description: "生成・創造を司る神。天孫降臨を主導した。",
    mythology: "天照大御神と共に高天原を統治。天孫ニニギの降臨を命じた重要な神。",
    blessing: "生産向上、子孫繁栄",
    category: "造化三神",
  },
  {
    id: "kamimusubi",
    deity: "神産巣日神",
    deityReading: "カミムスビノカミ",
    name: "出雲大社",
    location: "島根県出雲市",
    lat: 35.4017,
    lng: 132.6856,
    description: "生成・復活を司る神。大国主を蘇生させた。",
    mythology: "大国主が兄神たちに殺された際、蘇生させた母性的な神。",
    blessing: "病気平癒、再起",
    category: "造化三神",
  },

  // === 神世七代 ===
  {
    id: "izanagi",
    deity: "伊邪那岐命",
    deityReading: "イザナギノミコト",
    name: "伊弉諾神宮",
    location: "兵庫県淡路市",
    lat: 34.4614,
    lng: 134.8544,
    description: "国生み・神生みの男神。日本列島を生んだ。",
    mythology: "伊邪那美と共に天の浮橋に立ち、矛で海をかき混ぜ淤能碁呂島を作った。",
    blessing: "夫婦円満、縁結び、厄除け",
    category: "神世七代",
    relations: {
      spouse: ["izanami"],
      children: ["amaterasu", "tsukuyomi", "susanoo", "kagutsuchi", "ebisu", "oyamatsumi", "watatsumi", "shinatsuhiko"],
    },
  },
  {
    id: "izanami",
    deity: "伊邪那美命",
    deityReading: "イザナミノミコト",
    name: "花窟神社",
    location: "三重県熊野市",
    lat: 33.9236,
    lng: 136.0989,
    description: "国生み・神生みの女神。火神を生んで亡くなった。",
    mythology: "火之迦具土神を生んだ際に火傷を負い、黄泉国へ旅立った。",
    blessing: "子授け、安産、縁結び",
    category: "神世七代",
    relations: {
      spouse: ["izanagi"],
      children: ["amaterasu", "tsukuyomi", "susanoo", "kagutsuchi", "ebisu", "oyamatsumi", "watatsumi", "shinatsuhiko"],
    },
  },

  // === 三貴子 ===
  {
    id: "amaterasu",
    deity: "天照大御神",
    deityReading: "アマテラスオオミカミ",
    name: "伊勢神宮 内宮",
    location: "三重県伊勢市",
    lat: 34.4551,
    lng: 136.7256,
    description: "太陽を司る最高神。皇室の祖神。",
    mythology: "伊邪那岐の左目から生まれた。弟・須佐之男の乱暴に天岩戸に隠れ、世界は闇に包まれた。",
    blessing: "国家安泰、開運、所願成就",
    category: "三貴子",
    relations: {
      father: "izanagi",
      siblings: ["tsukuyomi", "susanoo"],
      children: ["amenooshihomimi", "amenohohi"],
    },
  },
  {
    id: "tsukuyomi",
    deity: "月読命",
    deityReading: "ツクヨミノミコト",
    name: "月読神社",
    location: "京都府京都市",
    lat: 34.9914,
    lng: 135.6847,
    description: "月を司る神。夜の世界を治める。",
    mythology: "伊邪那岐の右目から生まれた。夜の食国を治めるよう命じられた。",
    blessing: "航海安全、漁業繁栄、月のリズム",
    category: "三貴子",
    relations: {
      father: "izanagi",
      siblings: ["amaterasu", "susanoo"],
    },
  },
  {
    id: "susanoo",
    deity: "須佐之男命",
    deityReading: "スサノオノミコト",
    name: "八坂神社",
    location: "京都府京都市",
    lat: 35.0036,
    lng: 135.7785,
    description: "海原を司る神。ヤマタノオロチを退治した英雄。",
    mythology: "伊邪那岐の鼻から生まれた。高天原で乱暴を働き追放された後、出雲でヤマタノオロチを退治。",
    blessing: "厄除け、疫病退散、縁結び",
    category: "三貴子",
    relations: {
      father: "izanagi",
      siblings: ["amaterasu", "tsukuyomi"],
      spouse: ["kushinadahime"],
      children: ["suseribime", "ukanomitama"],
    },
  },

  // === 天岩戸神話の神々 ===
  {
    id: "amenouzume",
    deity: "天宇受賣命",
    deityReading: "アメノウズメノミコト",
    name: "佐瑠女神社",
    location: "三重県伊勢市",
    lat: 34.4875,
    lng: 136.7092,
    description: "芸能の女神。天岩戸の前で舞を踊った。",
    mythology: "天岩戸に隠れた天照大御神を誘い出すため、神懸かりの舞を踊り八百万の神を笑わせた。",
    blessing: "芸能上達、縁結び、鎮魂",
    category: "天岩戸",
    relations: {
      spouse: ["sarutahiko"],
    },
  },
  {
    id: "amenotajikarao",
    deity: "天手力男神",
    deityReading: "アメノタヂカラオノカミ",
    name: "戸隠神社 奥社",
    location: "長野県長野市",
    lat: 36.7561,
    lng: 138.0656,
    description: "怪力の神。天岩戸を開いた。",
    mythology: "天照大御神が岩戸を少し開けた瞬間、その手を取り引き出した。岩戸の扉を投げ飛ばした。",
    blessing: "スポーツ上達、開運、技芸向上",
    category: "天岩戸",
  },
  {
    id: "omoikane",
    deity: "思金神",
    deityReading: "オモイカネノカミ",
    name: "秩父神社",
    location: "埼玉県秩父市",
    lat: 35.9914,
    lng: 139.0856,
    description: "知恵の神。天岩戸作戦を立案した。",
    mythology: "天照大御神を誘い出す策を考え、八百万の神に指示を出した知恵者。",
    blessing: "学業成就、知恵向上、入試合格",
    category: "天岩戸",
  },
  {
    id: "amenokoyane",
    deity: "天児屋命",
    deityReading: "アメノコヤネノミコト",
    name: "春日大社",
    location: "奈良県奈良市",
    lat: 34.6814,
    lng: 135.8497,
    description: "祝詞の神。藤原氏の祖神。",
    mythology: "天岩戸の前で祝詞を奏上した。天孫降臨にも随行した。",
    blessing: "出世開運、国家安泰",
    category: "天岩戸",
  },
  {
    id: "futodama",
    deity: "布刀玉命",
    deityReading: "フトダマノミコト",
    name: "安房神社",
    location: "千葉県館山市",
    lat: 34.9539,
    lng: 139.8483,
    description: "祭祀の神。占いと祭具を司る。",
    mythology: "天岩戸神話で占いを行い、祭具を捧げた。忌部氏の祖神。",
    blessing: "産業振興、商売繁盛",
    category: "天岩戸",
  },
  {
    id: "ishikoridome",
    deity: "伊斯許理度売命",
    deityReading: "イシコリドメノミコト",
    name: "中山神社",
    location: "岡山県津山市",
    lat: 35.0847,
    lng: 134.0022,
    description: "鏡作りの神。八咫鏡を作った。",
    mythology: "天岩戸神話で八咫鏡を鋳造した。鏡作部の祖神。",
    blessing: "金属加工、技術向上",
    category: "天岩戸",
  },
  {
    id: "tamaoyabime",
    deity: "玉祖命",
    deityReading: "タマノオヤノミコト",
    name: "玉祖神社",
    location: "山口県防府市",
    lat: 34.0556,
    lng: 131.5547,
    description: "玉造りの神。八尺瓊勾玉を作った。",
    mythology: "天岩戸神話で勾玉を作った。玉造部の祖神。",
    blessing: "宝石・装飾品、技術向上",
    category: "天岩戸",
  },

  // === 出雲神話の神々 ===
  {
    id: "okuninushi",
    deity: "大国主命",
    deityReading: "オオクニヌシノミコト",
    name: "出雲大社",
    location: "島根県出雲市",
    lat: 35.4017,
    lng: 132.6856,
    description: "国造りの神。縁結びの神として名高い。",
    mythology: "兄神たちの迫害を乗り越え、少彦名神と共に国造りを行った。国譲りで幽世の王となった。",
    blessing: "縁結び、商売繁盛、病気平癒",
    category: "出雲神話",
    relations: {
      spouse: ["suseribime", "yagamihime"],
      children: ["kotoshironushi", "takeminakata"],
    },
  },
  {
    id: "sukunabikona",
    deity: "少彦名神",
    deityReading: "スクナビコナノカミ",
    name: "少彦名神社",
    location: "大阪府大阪市",
    lat: 34.6897,
    lng: 135.5022,
    description: "医薬・酒造の神。小さな姿の知恵者。",
    mythology: "海の彼方から来た小さな神。大国主と共に国造りを行い、医薬・温泉の知識を伝えた。",
    blessing: "病気平癒、医薬、酒造繁栄",
    category: "出雲神話",
    relations: {
      father: "kamimusubi",
    },
  },
  {
    id: "kotoshironushi",
    deity: "事代主神",
    deityReading: "コトシロヌシノカミ",
    name: "美保神社",
    location: "島根県松江市",
    lat: 35.5708,
    lng: 133.3092,
    description: "託宣の神。えびす様の原型とも。",
    mythology: "大国主の息子。国譲りの際、父に代わって承諾した。恵比須神と同一視される。",
    blessing: "商売繁盛、大漁満足",
    category: "出雲神話",
    relations: {
      father: "okuninushi",
      siblings: ["takeminakata"],
    },
  },
  {
    id: "takeminakata",
    deity: "建御名方神",
    deityReading: "タケミナカタノカミ",
    name: "諏訪大社 上社本宮",
    location: "長野県諏訪市",
    lat: 35.9983,
    lng: 138.1178,
    description: "武の神・風の神。諏訪の守護神。",
    mythology: "大国主の息子。国譲りに抵抗し建御雷神と力比べをしたが敗れ、諏訪に逃れた。",
    blessing: "武運長久、勝負運、風鎮め",
    category: "出雲神話",
    relations: {
      father: "okuninushi",
      siblings: ["kotoshironushi"],
    },
  },
  {
    id: "yagamihime",
    deity: "八上比売",
    deityReading: "ヤガミヒメ",
    name: "賣沼神社",
    location: "鳥取県鳥取市",
    lat: 35.4931,
    lng: 134.2369,
    description: "大国主の最初の妻。因幡の姫神。",
    mythology: "因幡の白兎神話で大国主と出会い、結ばれた。",
    blessing: "縁結び、子宝",
    category: "出雲神話",
    relations: {
      spouse: ["okuninushi"],
    },
  },
  {
    id: "suseribime",
    deity: "須勢理毘売命",
    deityReading: "スセリビメノミコト",
    name: "須佐神社",
    location: "島根県出雲市",
    lat: 35.2689,
    lng: 132.6822,
    description: "須佐之男命の娘。大国主の正妻。",
    mythology: "根の国で大国主と出会い、父の試練を乗り越える手助けをした。",
    blessing: "縁結び、夫婦円満",
    category: "出雲神話",
    relations: {
      father: "susanoo",
      spouse: ["okuninushi"],
    },
  },
  {
    id: "inaba_usagi",
    deity: "白兎神",
    deityReading: "シロウサギノカミ",
    name: "白兎神社",
    location: "鳥取県鳥取市",
    lat: 35.5208,
    lng: 134.0281,
    description: "因幡の白兎。縁結びの先駆け。",
    mythology: "ワニ（鮫）を騙して海を渡ろうとして皮を剥がれた。大国主に救われ、恋の成就を予言した。",
    blessing: "縁結び、皮膚病治癒",
    category: "出雲神話",
  },

  // === 天孫降臨の神々 ===
  {
    id: "ninigi",
    deity: "邇邇芸命",
    deityReading: "ニニギノミコト",
    name: "霧島神宮",
    location: "鹿児島県霧島市",
    lat: 31.8633,
    lng: 130.8683,
    description: "天孫。天照大御神の孫で日向に降臨した。",
    mythology: "三種の神器を授かり、高千穂峰に降臨。木花咲耶姫と結婚した。",
    blessing: "国家安泰、五穀豊穣",
    category: "天孫降臨",
    relations: {
      father: "amenooshihomimi",
      mother: "takuhadachijihime",
      spouse: ["konohanasakuya"],
      children: ["hoderi", "hoori", "hosuseri"],
    },
  },
  {
    id: "sarutahiko",
    deity: "猿田彦大神",
    deityReading: "サルタヒコオオカミ",
    name: "椿大神社",
    location: "三重県鈴鹿市",
    lat: 34.9456,
    lng: 136.4633,
    description: "道開きの神。天孫を案内した国津神。",
    mythology: "天孫降臨の際、高千穂への道案内を務めた。天宇受賣命と結婚。",
    blessing: "道開き、交通安全、方位除け",
    category: "天孫降臨",
    relations: {
      spouse: ["amenouzume"],
    },
  },
  {
    id: "konohanasakuya",
    deity: "木花咲耶姫命",
    deityReading: "コノハナサクヤヒメノミコト",
    name: "富士山本宮浅間大社",
    location: "静岡県富士宮市",
    lat: 35.2283,
    lng: 138.6106,
    description: "桜の女神。富士山の神。",
    mythology: "邇邇芸命と結婚。一夜で懐妊したことを疑われ、火中出産で潔白を証明した。",
    blessing: "安産、子育て、火難除け",
    category: "天孫降臨",
    relations: {
      father: "oyamatsumi",
      siblings: ["iwanagahime"],
      spouse: ["ninigi"],
      children: ["hoderi", "hoori", "hosuseri"],
    },
  },
  {
    id: "iwanagahime",
    deity: "石長比売命",
    deityReading: "イワナガヒメノミコト",
    name: "雲見浅間神社",
    location: "静岡県賀茂郡松崎町",
    lat: 34.7278,
    lng: 138.7653,
    description: "岩の女神。木花咲耶姫の姉。",
    mythology: "邇邇芸命に断られたため、人間は短命になったという。",
    blessing: "長寿、延命",
    category: "天孫降臨",
    relations: {
      father: "oyamatsumi",
      siblings: ["konohanasakuya"],
    },
  },
  {
    id: "oyamatsumi",
    deity: "大山祇神",
    deityReading: "オオヤマツミノカミ",
    name: "大山祇神社",
    location: "愛媛県今治市",
    lat: 34.2478,
    lng: 133.0022,
    description: "山の総元締め。木花咲耶姫の父。",
    mythology: "伊邪那岐・伊邪那美の子で山を司る。娘二人を邇邇芸命に嫁がせた。",
    blessing: "山林守護、鉱業、漁業",
    category: "天孫降臨",
    relations: {
      father: "izanagi",
      mother: "izanami",
      children: ["konohanasakuya", "iwanagahime"],
    },
  },

  // === 海幸・山幸神話 ===
  {
    id: "hoderi",
    deity: "火照命（海幸彦）",
    deityReading: "ホデリノミコト",
    name: "青島神社",
    location: "宮崎県宮崎市",
    lat: 31.8022,
    lng: 131.4703,
    description: "海幸彦。漁を司る。",
    mythology: "弟・山幸彦と釣り針を巡って争い、最終的に弟に服従した。隼人の祖とされる。",
    blessing: "漁業繁栄、航海安全",
    category: "海幸山幸",
    relations: {
      father: "ninigi",
      mother: "konohanasakuya",
      siblings: ["hoori", "hosuseri"],
    },
  },
  {
    id: "hoori",
    deity: "火遠理命（山幸彦）",
    deityReading: "ホオリノミコト",
    name: "鹿児島神宮",
    location: "鹿児島県霧島市",
    lat: 31.7264,
    lng: 130.7619,
    description: "山幸彦。狩りを司る。神武天皇の祖父。",
    mythology: "兄の釣り針を探して海神の宮へ行き、豊玉姫と結婚。潮満珠・潮干珠を得た。",
    blessing: "畜産、狩猟、縁結び",
    category: "海幸山幸",
    relations: {
      father: "ninigi",
      mother: "konohanasakuya",
      siblings: ["hoderi", "hosuseri"],
      spouse: ["toyotamahime"],
      children: ["ugayafukiaezu"],
    },
  },
  {
    id: "toyotamahime",
    deity: "豊玉姫命",
    deityReading: "トヨタマヒメノミコト",
    name: "海神神社",
    location: "長崎県対馬市",
    lat: 34.6036,
    lng: 129.3358,
    description: "海神の娘。山幸彦の妻。",
    mythology: "山幸彦と結婚。出産の姿を見られ、恥じて海に帰った。",
    blessing: "安産、漁業、航海安全",
    category: "海幸山幸",
    relations: {
      father: "watatsumi",
      siblings: ["tamayoribime"],
      spouse: ["hoori"],
      children: ["ugayafukiaezu"],
    },
  },
  {
    id: "tamayoribime",
    deity: "玉依姫命",
    deityReading: "タマヨリビメノミコト",
    name: "下鴨神社",
    location: "京都府京都市",
    lat: 35.0383,
    lng: 135.7725,
    description: "豊玉姫の妹。神武天皇の母。",
    mythology: "姉の代わりに甥（ウガヤフキアエズ）を育て、後に結婚して神武天皇を生んだ。",
    blessing: "縁結び、子育て、安産",
    category: "海幸山幸",
    relations: {
      father: "watatsumi",
      siblings: ["toyotamahime"],
      spouse: ["ugayafukiaezu"],
      children: ["jimmu"],
    },
  },
  {
    id: "ugayafukiaezu",
    deity: "鵜葺草葺不合命",
    deityReading: "ウガヤフキアエズノミコト",
    name: "鵜戸神宮",
    location: "宮崎県日南市",
    lat: 31.5847,
    lng: 131.4678,
    description: "山幸彦と豊玉姫の子。神武天皇の父。",
    mythology: "海辺の洞窟で生まれた。屋根を葺き終わる前に生まれたことから名がついた。",
    blessing: "安産、育児、縁結び",
    category: "海幸山幸",
    relations: {
      father: "hoori",
      mother: "toyotamahime",
      spouse: ["tamayoribime"],
      children: ["jimmu"],
    },
  },
  {
    id: "watatsumi",
    deity: "綿津見神",
    deityReading: "ワタツミノカミ",
    name: "志賀海神社",
    location: "福岡県福岡市",
    lat: 33.6597,
    lng: 130.3417,
    description: "海の神。豊玉姫の父。",
    mythology: "伊邪那岐の禊で生まれた海神。山幸彦を歓待し、娘を嫁がせた。",
    blessing: "航海安全、漁業繁栄",
    category: "海幸山幸",
    relations: {
      father: "izanagi",
      children: ["toyotamahime", "tamayoribime"],
    },
  },

  // === 国譲りの神々 ===
  {
    id: "takemikazuchi",
    deity: "建御雷神",
    deityReading: "タケミカヅチノカミ",
    name: "鹿島神宮",
    location: "茨城県鹿嶋市",
    lat: 35.9686,
    lng: 140.6308,
    description: "雷と剣の武神。国譲りの使者。",
    mythology: "天照大御神の命で出雲に降り、大国主に国譲りを迫った。",
    blessing: "武道上達、勝運、厄除け",
    category: "国譲り",
  },
  {
    id: "futsunushi",
    deity: "経津主神",
    deityReading: "フツヌシノカミ",
    name: "香取神宮",
    location: "千葉県香取市",
    lat: 35.8847,
    lng: 140.5278,
    description: "刀剣の神。建御雷神と共に国譲りを行った。",
    mythology: "建御雷神と共に出雲に降り、国譲りを成し遂げた。",
    blessing: "武道上達、国家鎮護",
    category: "国譲り",
  },
  {
    id: "amenohohi",
    deity: "天穂日命",
    deityReading: "アメノホヒノミコト",
    name: "出雲大社 北島国造館",
    location: "島根県出雲市",
    lat: 35.4022,
    lng: 132.6867,
    description: "天照大御神の子。出雲国造の祖。",
    mythology: "最初の国譲り使者だったが、大国主に心服して帰らなかった。",
    blessing: "農業、産業発展",
    category: "国譲り",
  },

  // === 火の神・竈の神 ===
  {
    id: "kagutsuchi",
    deity: "火之迦具土神",
    deityReading: "カグツチノカミ",
    name: "秋葉山本宮秋葉神社",
    location: "静岡県浜松市",
    lat: 35.0539,
    lng: 137.8536,
    description: "火の神。誕生時に母・伊邪那美を焼いた。",
    mythology: "誕生時に母を焼き殺し、父・伊邪那岐に斬られた。その体から多くの神が生まれた。",
    blessing: "火難除け、鍛冶",
    category: "火の神",
  },
  {
    id: "okitsuhiko",
    deity: "奥津日子神",
    deityReading: "オキツヒコノカミ",
    name: "愛宕神社",
    location: "京都府京都市",
    lat: 35.0581,
    lng: 135.6339,
    description: "竈の神。火の使用を司る。",
    mythology: "竈の神として家庭の火を守る。",
    blessing: "火防、家内安全",
    category: "火の神",
  },

  // === 食物・穀物の神 ===
  {
    id: "ukanomitama",
    deity: "宇迦之御魂神",
    deityReading: "ウカノミタマノカミ",
    name: "伏見稲荷大社",
    location: "京都府京都市",
    lat: 34.9671,
    lng: 135.7727,
    description: "稲の神、食物の神。稲荷神。",
    mythology: "須佐之男命の子とも、伊邪那岐・伊邪那美の子とも。穀物・食物を司る。",
    blessing: "五穀豊穣、商売繁盛",
    category: "食物神",
  },
  {
    id: "toyoukehime",
    deity: "豊受大御神",
    deityReading: "トヨウケノオオミカミ",
    name: "伊勢神宮 外宮",
    location: "三重県伊勢市",
    lat: 34.4875,
    lng: 136.7042,
    description: "食物・穀物の神。天照大御神の食事を司る。",
    mythology: "天照大御神の食事を調える神として丹波から迎えられた。",
    blessing: "五穀豊穣、産業振興",
    category: "食物神",
  },
  {
    id: "oogetsuhime",
    deity: "大気都比売神",
    deityReading: "オオゲツヒメノカミ",
    name: "上一宮大粟神社",
    location: "徳島県名西郡神山町",
    lat: 33.9583,
    lng: 134.3547,
    description: "食物の女神。阿波国の守護神。",
    mythology: "須佐之男命に殺されたが、その体から五穀が生じた。",
    blessing: "五穀豊穣、食物",
    category: "食物神",
  },
  {
    id: "wakaukanome",
    deity: "稚産霊神",
    deityReading: "ワクムスビノカミ",
    name: "熱田神宮",
    location: "愛知県名古屋市",
    lat: 35.1283,
    lng: 136.9089,
    description: "若々しい生命力の神。養蚕の神とも。",
    mythology: "火之迦具土神を斬った際に生まれた神。",
    blessing: "養蚕、農業",
    category: "食物神",
  },

  // === 水の神 ===
  {
    id: "mizuhanome",
    deity: "弥都波能売神",
    deityReading: "ミヅハノメノカミ",
    name: "丹生川上神社 中社",
    location: "奈良県吉野郡東吉野村",
    lat: 34.4236,
    lng: 136.0106,
    description: "水の女神。灌漑・水利を司る。",
    mythology: "伊邪那美が火傷を負った際の尿から生まれた。",
    blessing: "水難除け、雨乞い、農業",
    category: "水の神",
  },
  {
    id: "kuramitsuha",
    deity: "闇淤加美神",
    deityReading: "クラオカミノカミ",
    name: "貴船神社",
    location: "京都府京都市",
    lat: 35.1211,
    lng: 135.7631,
    description: "谷間の水を司る龍神。",
    mythology: "火之迦具土神を斬った剣の柄から滴る血から生まれた。",
    blessing: "降雨、止雨、縁結び",
    category: "水の神",
  },
  {
    id: "takaokami",
    deity: "高淤加美神",
    deityReading: "タカオカミノカミ",
    name: "丹生川上神社 上社",
    location: "奈良県吉野郡川上村",
    lat: 34.2981,
    lng: 135.9497,
    description: "山上の水を司る龍神。",
    mythology: "火之迦具土神を斬った剣から生まれた龍神。",
    blessing: "降雨、止雨、農業",
    category: "水の神",
  },

  // === 風の神 ===
  {
    id: "shinatsuhiko",
    deity: "志那都比古神",
    deityReading: "シナツヒコノカミ",
    name: "龍田大社",
    location: "奈良県生駒郡三郷町",
    lat: 34.5964,
    lng: 135.6822,
    description: "風の神。農耕に必要な風を司る。",
    mythology: "伊邪那岐・伊邪那美の子。朝霧を吹き払う風の神。",
    blessing: "風鎮め、航海安全、五穀豊穣",
    category: "風の神",
  },
  {
    id: "shinatobe",
    deity: "志那都比売神",
    deityReading: "シナトベノカミ",
    name: "伊勢神宮 風日祈宮",
    location: "三重県伊勢市",
    lat: 34.4547,
    lng: 136.7256,
    description: "風の女神。元寇の神風を起こした。",
    mythology: "志那都比古神と対になる風の女神。",
    blessing: "風鎮め、国家安泰",
    category: "風の神",
  },

  // === 雷・鍛冶の神 ===
  {
    id: "amenomahitotsu",
    deity: "天目一箇神",
    deityReading: "アメノマヒトツノカミ",
    name: "天目一神社",
    location: "兵庫県西脇市",
    lat: 34.9917,
    lng: 134.9658,
    description: "鍛冶の神。一つ目の神。",
    mythology: "製鉄・鍛冶を司る神。鍛冶師は片目をつぶって火加減を見ることから。",
    blessing: "鍛冶、製鉄",
    category: "鍛冶神",
  },

  // === 土の神 ===
  {
    id: "haniyasu",
    deity: "埴安神",
    deityReading: "ハニヤスノカミ",
    name: "土師神社",
    location: "大阪府藤井寺市",
    lat: 34.5694,
    lng: 135.6008,
    description: "土・粘土の神。陶器・瓦を司る。",
    mythology: "伊邪那美が火傷を負った際の大便から生まれた。",
    blessing: "土木、陶芸、建築",
    category: "土の神",
  },

  // === 神武東征の神々 ===
  {
    id: "jimmu",
    deity: "神武天皇",
    deityReading: "ジンムテンノウ",
    name: "橿原神宮",
    location: "奈良県橿原市",
    lat: 34.4544,
    lng: 135.7831,
    description: "初代天皇。日向から東征し大和を平定。",
    mythology: "天照大御神の子孫。日向を出発し、大和で初代天皇として即位した。",
    blessing: "開運、勝運、建国",
    category: "神武東征",
    relations: {
      father: "ugayafukiaezu",
      mother: "tamayoribime",
    },
  },
  {
    id: "yatagarasu",
    deity: "八咫烏",
    deityReading: "ヤタガラス",
    name: "熊野本宮大社",
    location: "和歌山県田辺市",
    lat: 33.8403,
    lng: 135.7739,
    description: "三本足の霊鳥。神武天皇を導いた。",
    mythology: "高皇産霊尊が遣わした霊鳥。神武天皇を熊野から大和へ導いた。",
    blessing: "導き、勝運",
    category: "神武東征",
  },
  {
    id: "nigihayahi",
    deity: "饒速日命",
    deityReading: "ニギハヤヒノミコト",
    name: "石切劔箭神社",
    location: "大阪府東大阪市",
    lat: 34.6789,
    lng: 135.6508,
    description: "物部氏の祖神。神武天皇より先に大和に降臨。",
    mythology: "天照大御神から十種神宝を授かり、大和に降臨した。",
    blessing: "病気平癒、でんぼ（腫物）封じ",
    category: "神武東征",
  },

  // === 日本武尊関連 ===
  {
    id: "yamatotakeru",
    deity: "日本武尊",
    deityReading: "ヤマトタケルノミコト",
    name: "大鳥大社",
    location: "大阪府堺市",
    lat: 34.5331,
    lng: 135.4914,
    description: "伝説的英雄。東国征伐を行った。",
    mythology: "景行天皇の皇子。熊襲征伐、東国征伐で活躍。伊吹山で病に倒れ、白鳥となった。",
    blessing: "武運、開拓、国土平定",
    category: "日本武尊",
  },
  {
    id: "otohibime",
    deity: "弟橘媛",
    deityReading: "オトタチバナヒメ",
    name: "走水神社",
    location: "神奈川県横須賀市",
    lat: 35.2547,
    lng: 139.7242,
    description: "日本武尊の妃。海を鎮めるために入水。",
    mythology: "東征の際、荒れる海を鎮めるため自ら海に身を投じた。",
    blessing: "海上安全、縁結び",
    category: "日本武尊",
  },
  {
    id: "miyazuhime",
    deity: "宮簀媛命",
    deityReading: "ミヤズヒメノミコト",
    name: "熱田神宮",
    location: "愛知県名古屋市",
    lat: 35.1283,
    lng: 136.9089,
    description: "日本武尊の妃。草薙剣を祀った。",
    mythology: "日本武尊から草薙剣を預かり、熱田に祀った。",
    blessing: "縁結び、家内安全",
    category: "日本武尊",
  },

  // === その他重要な神々 ===
  {
    id: "hachiman",
    deity: "八幡神（応神天皇）",
    deityReading: "ハチマンシン",
    name: "宇佐神宮",
    location: "大分県宇佐市",
    lat: 33.5264,
    lng: 131.3753,
    description: "武運の神。全国八幡宮の総本宮。",
    mythology: "応神天皇を神格化。源氏の氏神として武家に崇敬された。",
    blessing: "武運長久、勝運、国家鎮護",
    category: "八幡神",
  },
  {
    id: "sumiyoshi",
    deity: "住吉三神",
    deityReading: "スミヨシサンジン",
    name: "住吉大社",
    location: "大阪府大阪市",
    lat: 34.6128,
    lng: 135.4931,
    description: "海の神。航海安全を司る。",
    mythology: "伊邪那岐の禊で生まれた底筒男命・中筒男命・表筒男命の三神。",
    blessing: "航海安全、和歌、産業",
    category: "住吉神",
  },
  {
    id: "munakata",
    deity: "宗像三女神",
    deityReading: "ムナカタサンジョシン",
    name: "宗像大社",
    location: "福岡県宗像市",
    lat: 33.8306,
    lng: 130.5144,
    description: "海上交通の守護神。天照大御神の子。",
    mythology: "天照大御神と須佐之男命の誓約で生まれた。玄界灘の海上交通を守護。",
    blessing: "海上安全、交通安全",
    category: "宗像神",
  },
  {
    id: "tenjin",
    deity: "天神（菅原道真）",
    deityReading: "テンジン",
    name: "太宰府天満宮",
    location: "福岡県太宰府市",
    lat: 33.5192,
    lng: 130.5347,
    description: "学問の神。菅原道真を神格化。",
    mythology: "平安時代の学者・政治家。無実の罪で大宰府に左遷され、死後神として祀られた。",
    blessing: "学業成就、受験合格",
    category: "天神",
  },
  {
    id: "kasuga",
    deity: "春日神",
    deityReading: "カスガノカミ",
    name: "春日大社",
    location: "奈良県奈良市",
    lat: 34.6814,
    lng: 135.8497,
    description: "藤原氏の氏神。四柱の神を祀る。",
    mythology: "武甕槌命・経津主神・天児屋命・比売神の四柱。藤原氏により祀られた。",
    blessing: "国家安泰、武運、出世",
    category: "春日神",
  },
  {
    id: "benzaiten",
    deity: "弁財天",
    deityReading: "ベンザイテン",
    name: "江島神社",
    location: "神奈川県藤沢市",
    lat: 35.2997,
    lng: 139.4797,
    description: "芸能・財福の女神。七福神の一柱。",
    mythology: "インドの河川の女神サラスヴァティーが日本で習合した。",
    blessing: "芸能上達、財運、縁結び",
    category: "弁財天",
  },
  {
    id: "ebisu",
    deity: "蛭子神（恵比寿）",
    deityReading: "ヒルコノカミ",
    name: "西宮神社",
    location: "兵庫県西宮市",
    lat: 34.7378,
    lng: 135.3428,
    description: "商売繁盛の神。七福神の一柱。",
    mythology: "伊邪那岐・伊邪那美の最初の子。不具だったため流された。",
    blessing: "商売繁盛、大漁",
    category: "恵比寿",
  },
  {
    id: "omiwa",
    deity: "大物主神",
    deityReading: "オオモノヌシノカミ",
    name: "大神神社",
    location: "奈良県桜井市",
    lat: 34.5264,
    lng: 135.8542,
    description: "三輪山の神。大国主の和魂。",
    mythology: "大国主の国造りを助けた神。三輪山そのものを御神体とする。",
    blessing: "病気平癒、醸造、縁結び",
    category: "大物主",
  },

  // === 新規追加の神々 ===

  // 天孫系譜補完
  {
    id: "amenooshihomimi",
    deity: "天忍穂耳命",
    deityReading: "アメノオシホミミノミコト",
    name: "英彦山神宮",
    location: "福岡県田川郡添田町",
    lat: 33.4764,
    lng: 130.9278,
    description: "天照大御神の子。邇邇芸命の父。",
    mythology: "天照大御神と須佐之男命の誓約で生まれた。葦原中国平定を命じられたが辞退し、息子の邇邇芸命を降臨させた。",
    blessing: "勝運、開運、農業繁栄",
    category: "天孫降臨",
    relations: {
      mother: "amaterasu",
      spouse: ["takuhadachijihime"],
      children: ["ninigi"],
    },
  },
  {
    id: "takuhadachijihime",
    deity: "栲幡千千姫命",
    deityReading: "タクハタチジヒメノミコト",
    name: "機物神社",
    location: "大阪府交野市",
    lat: 34.7856,
    lng: 135.6708,
    description: "機織りの女神。邇邇芸命の母。",
    mythology: "高皇産霊尊の娘で、天忍穂耳命の妃となった。織物の技術を司る。",
    blessing: "織物、裁縫上達、良縁",
    category: "天孫降臨",
    relations: {
      father: "takamimusubi",
      spouse: ["amenooshihomimi"],
      children: ["ninigi"],
    },
  },

  // 出雲神話補完
  {
    id: "kushinadahime",
    deity: "櫛名田比売",
    deityReading: "クシナダヒメ",
    name: "八重垣神社",
    location: "島根県松江市",
    lat: 35.4322,
    lng: 133.1058,
    description: "須佐之男命の妻。ヤマタノオロチの生贄から救われた。",
    mythology: "ヤマタノオロチに捧げられる予定だったが、須佐之男命に救われ妻となった。",
    blessing: "縁結び、夫婦円満、災難除け",
    category: "出雲神話",
    relations: {
      spouse: ["susanoo"],
      children: ["suseribime"],
    },
  },

  // 海幸山幸補完
  {
    id: "hosuseri",
    deity: "火須勢理命",
    deityReading: "ホスセリノミコト",
    name: "霧島東神社",
    location: "宮崎県西諸県郡高原町",
    lat: 31.9133,
    lng: 131.0292,
    description: "邇邇芸命の子。火照命・火遠理命の兄弟。",
    mythology: "邇邇芸命と木花咲耶姫の間に生まれた三兄弟の一柱。神話での記述は少ない。",
    blessing: "家内安全、繁栄",
    category: "海幸山幸",
    relations: {
      father: "ninigi",
      mother: "konohanasakuya",
      siblings: ["hoderi", "hoori"],
    },
  },

  // 造化三神補完
  {
    id: "kuninotokotachi",
    deity: "国之常立神",
    deityReading: "クニノトコタチノカミ",
    name: "玉置神社",
    location: "奈良県吉野郡十津川村",
    lat: 33.8558,
    lng: 135.8681,
    description: "国土の永遠性を象徴する神。神世七代の最初の神。",
    mythology: "天地開闢の後、葦原に国土が形成される際に現れた。独神として身を隠した。",
    blessing: "国土安泰、開運、心願成就",
    category: "神世七代",
  },
  {
    id: "umashiashikabihikoji",
    deity: "宇摩志阿斯訶備比古遅神",
    deityReading: "ウマシアシカビヒコヂノカミ",
    name: "物部神社",
    location: "島根県大田市",
    lat: 35.2056,
    lng: 132.4728,
    description: "生命力の神。別天津神の一柱。",
    mythology: "天地開闘の最初期、活力ある生命の兆しとして現れた神。",
    blessing: "生命力、活力向上",
    category: "造化三神",
  },

  // 八幡神関連
  {
    id: "jinguukougou",
    deity: "神功皇后",
    deityReading: "ジングウコウゴウ",
    name: "香椎宮",
    location: "福岡県福岡市",
    lat: 33.6567,
    lng: 130.4531,
    description: "応神天皇の母。三韓征伐を行った伝説の女傑。",
    mythology: "身重の身で三韓征伐を行い、帰国後に応神天皇を産んだ。武内宿禰が補佐した。",
    blessing: "安産、勝運、国家安泰",
    category: "八幡神",
    relations: {
      children: ["hachiman"],
    },
  },

  // 伊勢関連
  {
    id: "yamatohime",
    deity: "倭姫命",
    deityReading: "ヤマトヒメノミコト",
    name: "倭姫宮",
    location: "三重県伊勢市",
    lat: 34.4622,
    lng: 136.7247,
    description: "第11代垂仁天皇の皇女。伊勢神宮を創建。",
    mythology: "天照大御神の御杖代として諸国を巡り、伊勢の地に神宮を定めた。",
    blessing: "心願成就、導き、旅行安全",
    category: "三貴子",
  },

  // 熊野関連
  {
    id: "kumanogongen",
    deity: "熊野権現",
    deityReading: "クマノゴンゲン",
    name: "熊野速玉大社",
    location: "和歌山県新宮市",
    lat: 33.7283,
    lng: 135.9894,
    description: "熊野三山の神。修験道の聖地。",
    mythology: "伊邪那岐命・伊邪那美命とも同一視される。熊野三山を守護する。",
    blessing: "蘇り、再生、厄除け",
    category: "熊野",
  },
  {
    id: "kumanofusumi",
    deity: "熊野夫須美大神",
    deityReading: "クマノフスミノオオカミ",
    name: "熊野那智大社",
    location: "和歌山県東牟婁郡那智勝浦町",
    lat: 33.6708,
    lng: 135.8875,
    description: "熊野三山の神。那智の滝を御神体とする。",
    mythology: "伊邪那美命の別名とも。結びの神として信仰される。",
    blessing: "縁結び、願望成就、延命",
    category: "熊野",
  },

  // 山岳信仰
  {
    id: "hieyama",
    deity: "大山咋神",
    deityReading: "オオヤマクイノカミ",
    name: "日吉大社",
    location: "滋賀県大津市",
    lat: 35.0706,
    lng: 135.8686,
    description: "比叡山の地主神。山王権現とも。",
    mythology: "大年神の子。比叡山に鎮座し、延暦寺の守護神となった。",
    blessing: "方除け、厄除け、縁結び",
    category: "山岳信仰",
    relations: {
      father: "ootoshi",
    },
  },
  {
    id: "konohanasakuyahikosawa",
    deity: "木花之佐久夜毘古",
    deityReading: "コノハナノサクヤビコ",
    name: "浅間神社 (山梨)",
    location: "山梨県笛吹市",
    lat: 35.6417,
    lng: 138.6439,
    description: "山の神。木花咲耶姫と対になる男神。",
    mythology: "山々の花々を司る。富士山周辺で祀られる。",
    blessing: "山林守護、開運",
    category: "山岳信仰",
  },

  // 食物神追加
  {
    id: "ootoshi",
    deity: "大年神",
    deityReading: "オオトシノカミ",
    name: "大歳神社",
    location: "兵庫県神戸市",
    lat: 34.6911,
    lng: 135.1528,
    description: "年穀の神。稲の実りを司る。",
    mythology: "須佐之男命と神大市比売の子。年神信仰の中心的存在。",
    blessing: "五穀豊穣、商売繁盛",
    category: "食物神",
    relations: {
      father: "susanoo",
      children: ["hieyama"],
    },
  },
  {
    id: "inari",
    deity: "稲荷大神",
    deityReading: "イナリオオカミ",
    name: "笠間稲荷神社",
    location: "茨城県笠間市",
    lat: 36.3836,
    lng: 140.2547,
    description: "稲の神。農業・商業の守護神。",
    mythology: "宇迦之御魂神と同一視される。狐を神使とする。",
    blessing: "五穀豊穣、商売繁盛、家内安全",
    category: "食物神",
  },

  // 技術・職業の神
  {
    id: "kanayamabiko",
    deity: "金山彦神",
    deityReading: "カナヤマビコノカミ",
    name: "金山神社",
    location: "岐阜県不破郡垂井町",
    lat: 35.3736,
    lng: 136.5275,
    description: "鉱山・金属の神。鍛冶の守護神。",
    mythology: "伊邪那美命が火傷を負った際の嘔吐物から生まれた。",
    blessing: "金属加工、鉱業、金運",
    category: "鍛冶神",
    relations: {
      mother: "izanami",
    },
  },

  // 芸能・文化の神
  {
    id: "sukunahikona_another",
    deity: "薬祖神",
    deityReading: "ヤクソシン",
    name: "神田明神",
    location: "東京都千代田区",
    lat: 35.7019,
    lng: 139.7681,
    description: "医薬の神。少彦名神の別称。",
    mythology: "大国主命と共に国造りを行い、医薬の道を開いた。",
    blessing: "病気平癒、健康長寿、医療関係者守護",
    category: "出雲神話",
  },

  // 武神追加
  {
    id: "takeiwatatsu",
    deity: "建磐龍命",
    deityReading: "タケイワタツノミコト",
    name: "阿蘇神社",
    location: "熊本県阿蘇市",
    lat: 32.9483,
    lng: 131.1225,
    description: "阿蘇開拓の祖神。神武天皇の孫。",
    mythology: "神武天皇の孫として阿蘇地方を開拓した。健磐龍命とも。",
    blessing: "開拓、五穀豊穣、厄除け",
    category: "神武東征",
    relations: {
      father: "jimmu",
    },
  },

  // 水神追加
  {
    id: "seoritsu",
    deity: "瀬織津姫",
    deityReading: "セオリツヒメ",
    name: "瀬織津姫神社",
    location: "岩手県遠野市",
    lat: 39.3375,
    lng: 141.5389,
    description: "祓いの女神。川の流れで罪を洗い流す。",
    mythology: "大祓詞に登場する四柱の祓戸大神の一柱。",
    blessing: "罪穢祓い、水難除け、心身浄化",
    category: "水の神",
  },

  // 星神
  {
    id: "amatsumikaboshi",
    deity: "天津甕星",
    deityReading: "アマツミカボシ",
    name: "大甕神社",
    location: "茨城県日立市",
    lat: 36.5731,
    lng: 140.6483,
    description: "星の神。天津神に従わなかった唯一の神。",
    mythology: "天孫降臨前、高天原に従わず最後まで抵抗した星の神。",
    blessing: "厄除け、方位除け、開運",
    category: "星神",
  },

  // 道祖神・境界の神
  {
    id: "kunado",
    deity: "岐神",
    deityReading: "クナドノカミ",
    name: "道祖神社",
    location: "京都府京都市",
    lat: 34.9889,
    lng: 135.7597,
    description: "道の分岐点を守る神。悪霊の侵入を防ぐ。",
    mythology: "伊邪那岐命が黄泉国から戻る際に現れた神。",
    blessing: "旅行安全、災難除け、縁結び",
    category: "道祖神",
  },

  // 海神追加
  {
    id: "shiotsuchiooji",
    deity: "塩椎神",
    deityReading: "シオツチノオジ",
    name: "鹽竈神社",
    location: "宮城県塩竈市",
    lat: 38.3192,
    lng: 141.0203,
    description: "潮の神。製塩技術を伝えた。",
    mythology: "山幸彦を海神の宮へ導いた老神。塩土老翁とも。",
    blessing: "航海安全、製塩、延命長寿",
    category: "海幸山幸",
  },

  // 雷神追加
  {
    id: "takemikazuchiwake",
    deity: "武甕槌命",
    deityReading: "タケミカヅチノミコト",
    name: "武蔵一宮氷川神社",
    location: "埼玉県さいたま市",
    lat: 35.9094,
    lng: 139.6294,
    description: "雷と武の神。関東の総鎮守。",
    mythology: "国譲りで活躍した武神。関東で広く祀られる。",
    blessing: "武運、勝運、厄除け",
    category: "国譲り",
  },

  // 農業神追加
  {
    id: "mitoshikami",
    deity: "御歳神",
    deityReading: "ミトシノカミ",
    name: "葛木御歳神社",
    location: "奈良県御所市",
    lat: 34.4344,
    lng: 135.7428,
    description: "穀物の神。大年神の子。",
    mythology: "正月に迎える年神の一柱。穀物の豊作を司る。",
    blessing: "五穀豊穣、家内安全",
    category: "食物神",
    relations: {
      father: "ootoshi",
    },
  },

  // 宗像三女神個別
  {
    id: "tagorihime",
    deity: "田心姫神",
    deityReading: "タゴリヒメノカミ",
    name: "宗像大社 沖津宮",
    location: "福岡県宗像市（沖ノ島）",
    lat: 34.2428,
    lng: 130.1047,
    description: "宗像三女神の一柱。沖ノ島に鎮座。",
    mythology: "天照大御神と須佐之男命の誓約で生まれた。海上交通を守護する。",
    blessing: "海上安全、交通安全",
    category: "宗像神",
    relations: {
      mother: "amaterasu",
      siblings: ["tagitsuhime", "ichikishimahime"],
    },
  },
  {
    id: "tagitsuhime",
    deity: "湍津姫神",
    deityReading: "タギツヒメノカミ",
    name: "宗像大社 中津宮",
    location: "福岡県宗像市（大島）",
    lat: 33.9019,
    lng: 130.4383,
    description: "宗像三女神の一柱。大島に鎮座。",
    mythology: "天照大御神と須佐之男命の誓約で生まれた。",
    blessing: "海上安全、芸能上達",
    category: "宗像神",
    relations: {
      mother: "amaterasu",
      siblings: ["tagorihime", "ichikishimahime"],
    },
  },
  {
    id: "ichikishimahime",
    deity: "市杵島姫神",
    deityReading: "イチキシマヒメノカミ",
    name: "厳島神社",
    location: "広島県廿日市市",
    lat: 34.2961,
    lng: 132.3197,
    description: "宗像三女神の一柱。芸能・財運の女神。",
    mythology: "弁財天と習合し、芸能・財福の神として信仰される。",
    blessing: "芸能上達、財運、交通安全",
    category: "宗像神",
    relations: {
      mother: "amaterasu",
      siblings: ["tagorihime", "tagitsuhime"],
    },
  },

  // 住吉三神個別
  {
    id: "sokotsutsunoo",
    deity: "底筒男命",
    deityReading: "ソコツツノオノミコト",
    name: "住吉神社 (下関)",
    location: "山口県下関市",
    lat: 33.9592,
    lng: 130.9411,
    description: "住吉三神の一柱。海底を司る。",
    mythology: "伊邪那岐命の禊で海底から生まれた。",
    blessing: "航海安全、産業振興",
    category: "住吉神",
    relations: {
      father: "izanagi",
      siblings: ["nakatsutsunoo", "uwatsutsunoo"],
    },
  },
  {
    id: "nakatsutsunoo",
    deity: "中筒男命",
    deityReading: "ナカツツノオノミコト",
    name: "住吉神社 (福岡)",
    location: "福岡県福岡市",
    lat: 33.5894,
    lng: 130.3533,
    description: "住吉三神の一柱。海中を司る。",
    mythology: "伊邪那岐命の禊で海中から生まれた。",
    blessing: "航海安全、漁業繁栄",
    category: "住吉神",
    relations: {
      father: "izanagi",
      siblings: ["sokotsutsunoo", "uwatsutsunoo"],
    },
  },
  {
    id: "uwatsutsunoo",
    deity: "表筒男命",
    deityReading: "ウワツツノオノミコト",
    name: "住吉神社 (長門)",
    location: "山口県下関市",
    lat: 33.9617,
    lng: 130.9425,
    description: "住吉三神の一柱。海面を司る。",
    mythology: "伊邪那岐命の禊で海面から生まれた。",
    blessing: "航海安全、和歌上達",
    category: "住吉神",
    relations: {
      father: "izanagi",
      siblings: ["sokotsutsunoo", "nakatsutsunoo"],
    },
  },
];

// カテゴリ一覧
export const categories = [
  "造化三神",
  "神世七代",
  "三貴子",
  "天岩戸",
  "出雲神話",
  "天孫降臨",
  "海幸山幸",
  "国譲り",
  "火の神",
  "食物神",
  "水の神",
  "風の神",
  "鍛冶神",
  "土の神",
  "神武東征",
  "日本武尊",
  "八幡神",
  "住吉神",
  "宗像神",
  "天神",
  "春日神",
  "弁財天",
  "恵比寿",
  "大物主",
  "熊野",
  "山岳信仰",
  "星神",
  "道祖神",
];
